# Generated by Django 5.1.1 on 2024-09-06 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0005_alter_project_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(default='', max_length=100, verbose_name='Presupuesto - Cotización')),
                ('day', models.PositiveIntegerField()),
                ('total_sol_partial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_dollar_partial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sol_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_dollar_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exchange', models.DecimalField(decimal_places=3, default=3.75, max_digits=10)),
                ('quote_number', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('money', models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], default='USD', max_length=3)),
                ('tax', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('service_time', models.CharField(blank=True, max_length=100, null=True)),
                ('billing', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_time', models.CharField(blank=True, max_length=100, null=True)),
                ('not_incluyed', models.TextField(blank=True, null=True)),
                ('administration_expenses', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('administration_expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utility', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('utility_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='project.project', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('real_price', models.FloatField(default=0)),
                ('real_price_day', models.FloatField(default=0)),
                ('measure_unit', models.CharField(blank=True, default='', max_length=50)),
                ('useful_life', models.PositiveIntegerField(default=365)),
                ('price_item_project', models.FloatField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
