# Generated by Django 5.1.1 on 2024-09-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Equipo', 'Equipo'), ('EPPS', 'Epps'), ('Material', 'Material'), ('Consumible', 'Consumible'), ('Herramienta', 'Herramienta'), ('Mano de obra', 'Manodeobra')], default='Equipo', max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sap', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(default='UND', max_length=100)),
                ('apply_price_per_day', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(default='', max_length=100)),
                ('budget_number', models.CharField(blank=True, max_length=10)),
                ('budget_days', models.PositiveIntegerField()),
                ('budget_date', models.DateField()),
                ('budget_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_expenses', models.DecimalField(choices=[(5.0, '5%'), (8.0, '8%'), (10.0, '10%')], decimal_places=2, default=5.0, max_digits=5)),
                ('budget_utility', models.DecimalField(choices=[(5.0, '5%'), (8.0, '8%'), (10.0, '10%')], decimal_places=2, default=5.0, max_digits=5)),
                ('budget_final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_deliverytime', models.CharField(blank=True, choices=[('2 days', '2 Días'), ('1 week', '1 Semana'), ('2 weeks', '2 Semanas'), ('1 month', '1 Mes'), ('2 months', '2 Meses'), ('6 months', '6 Meses'), ('1 year', '1 Año'), ('2 years', '2 Años'), ('3 years', '3 Años')], max_length=100, null=True)),
                ('budget_servicetime', models.CharField(blank=True, choices=[('2 days', '2 Días'), ('1 week', '1 Semana'), ('2 weeks', '2 Semanas'), ('1 month', '1 Mes'), ('2 months', '2 Meses'), ('6 months', '6 Meses'), ('1 year', '1 Año'), ('2 years', '2 Años'), ('3 years', '3 Años')], max_length=100, null=True)),
                ('budget_warrantytime', models.CharField(blank=True, choices=[('2 days', '2 Días'), ('1 week', '1 Semana'), ('2 weeks', '2 Semanas'), ('1 month', '1 Mes'), ('2 months', '2 Meses'), ('6 months', '6 Meses'), ('1 year', '1 Año'), ('2 years', '2 Años'), ('3 years', '3 Años')], max_length=100, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budget.catalogitem')),
            ],
        ),
    ]
