# Generated by Django 5.1.1 on 2024-10-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='apply_price_per_day',
        ),
    ]
