# Generated by Django 5.1.1 on 2024-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_catalogitem_apply_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='apply_price_per_day',
            field=models.BooleanField(default=True),
        ),
    ]
