# Generated by Django 5.1.1 on 2024-10-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_catalogitem_apply_price_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='apply_price_per_day',
        ),
    ]
