# Generated by Django 5.1.1 on 2024-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='measurement',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
