# Generated by Django 5.1.1 on 2024-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budgetitem_item_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Equipo', 'Equipo'), ('EPPS', 'Epps'), ('Material', 'Material'), ('Consumible', 'Consumible'), ('Herramienta', 'Herramienta')], default='Equipo', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
