# Generated by Django 5.1.1 on 2024-09-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budgetitem_item_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Diario')),
                ('lifespan', models.PositiveIntegerField(verbose_name='Tiempo de Vida (días)')),
                ('item_class', models.CharField(choices=[('herramienta', 'Herramienta'), ('material', 'Material'), ('consumible', 'Consumible')], max_length=50, verbose_name='Clase de Ítem')),
            ],
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budget.item'),
        ),
    ]
