# Generated by Django 5.1.1 on 2024-09-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_item_alter_budgetitem_item'),
        ('logistic_inventory', '0015_alter_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='logistic_inventory.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
