# Generated by Django 5.1.1 on 2024-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_budgetitem_item_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='final_price',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_deliverytime',
            field=models.CharField(blank=True, choices=[('2 days', '2 Días'), ('1 week', '1 Semana'), ('2 weeks', '2 Semanas'), ('1 month', '1 Mes'), ('2 months', '2 Meses'), ('6 months', '6 Meses'), ('1 year', '1 Año'), ('2 years', '2 Años'), ('3 years', '3 Años')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_servicetime',
            field=models.CharField(blank=True, choices=[('2 days', '2 Días'), ('1 week', '1 Semana'), ('2 weeks', '2 Semanas'), ('1 month', '1 Mes'), ('2 months', '2 Meses'), ('6 months', '6 Meses'), ('1 year', '1 Año'), ('2 years', '2 Años'), ('3 years', '3 Años')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_utility',
            field=models.DecimalField(choices=[(5.0, '5%'), (8.0, '8%'), (10.0, '10%')], decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_warrantytime',
            field=models.CharField(blank=True, choices=[('2 days', '2 Días'), ('1 week', '1 Semana'), ('2 weeks', '2 Semanas'), ('1 month', '1 Mes'), ('2 months', '2 Meses'), ('6 months', '6 Meses'), ('1 year', '1 Año'), ('2 years', '2 Años'), ('3 years', '3 Años')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_expenses',
            field=models.DecimalField(choices=[(5.0, '5%'), (8.0, '8%'), (10.0, '10%')], decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
