# Generated by Django 5.1.1 on 2024-09-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_catalogitem'),
        ('budget', '0009_remove_budgetitem_final_price_and_more'),
    ]

    operations = [
    ]
