# Generated by Django 5.1.1 on 2024-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_rename_name_catalogitem_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
