# Generated by Django 5.1.1 on 2024-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_catalogitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='unit',
            field=models.CharField(default='UND', max_length=100),
        ),
    ]
