# Generated by Django 5.1.1 on 2024-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_catalogitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='apply_price_per_day',
            field=models.BooleanField(default=True),
        ),
    ]
