# Generated by Django 5.1.1 on 2024-09-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_catalogitem_apply_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.CharField(choices=[('Equipo', 'Equipo'), ('EPPS', 'Epps'), ('Material', 'Material'), ('Consumible', 'Consumible'), ('Herramienta', 'Herramienta'), ('Mano de obra', 'Manodeobra')], default='Equipo', max_length=100),
        ),
    ]
