# Generated by Django 5.1.1 on 2024-09-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapcode', models.IntegerField(max_length=50)),
                ('project', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_order_sales.salesorder')),
            ],
        ),
    ]
