# Generated by Django 5.1.1 on 2024-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatements',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='class_pay',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='sap_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='type_pay',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='sap_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankStatements',
        ),
    ]
