# Generated by Django 5.1.1 on 2024-10-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_of_measurement',
            field=models.CharField(default='UND', max_length=255),
        ),
    ]
