# Generated by Django 5.1.1 on 2024-09-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='remaining_requirement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
