# Generated by Django 5.1.1 on 2024-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='sapcode',
            field=models.PositiveBigIntegerField(),
        ),
    ]
