# Generated by Django 5.1.1 on 2024-09-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0002_salesorderitem_remaining_requirement'),
        ('logistic_suppliers', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic_suppliers.suppliers'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sapcode',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
