# Generated by Django 5.1.1 on 2024-09-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0004_salesorderitem_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='salesorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting_order_sales.salesorder'),
        ),
    ]
