# Generated by Django 5.1.1 on 2024-09-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0005_alter_salesorderitem_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField()),
                ('requested_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Encargado')),
                ('acepted', models.BooleanField(default=True)),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounting_order_sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(default='', max_length=50)),
                ('class_pay', models.CharField(default='', max_length=50)),
                ('type_pay', models.CharField(default='', max_length=50)),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('mov_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('purchaseorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting_order_sales.purchaseorder')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_order_sales.salesorderitem')),
            ],
        ),
    ]
