# Generated by Django 5.1.1 on 2024-09-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_contract_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='client',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
