# Generated by Django 5.1.1 on 2024-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_control_technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='techniciantask',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='techniciantask',
            name='object',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='techniciantask',
            name='verb',
            field=models.CharField(max_length=150),
        ),
    ]
