# Generated by Django 5.1.1 on 2024-11-14 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_control_technician', '0002_alter_techniciantask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciancard',
            name='start_hour',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
