# Generated by Django 5.1.1 on 2024-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts_pdfs/'),
        ),
    ]
