# Generated by Django 5.1.1 on 2024-09-19 17:03

import client_crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crm', '0002_contract_contract_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to=client_crm.models.rename_file),
        ),
    ]
