# Generated by Django 5.1.1 on 2024-09-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EQUIPOS', 'Equipos'), ('EPPS', 'EPPS'), ('TRANSPORTE', 'Transporte'), ('MATERIALES', 'Materiales'), ('CONSUMIBLES', 'Consumibles'), ('MANODEOBRA', 'Mano de Obra'), ('HERRAMIENTAS', 'Herramientas')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('unit_measure', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic_inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic_inventory.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic_inventory.producttype')),
            ],
        ),
    ]
