# Generated by Django 5.1.1 on 2024-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code_qr',
            field=models.ImageField(blank=True, null=True, upload_to='item_qr/', verbose_name='img'),
        ),
    ]
