# Generated by Django 5.1.1 on 2024-09-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('EQUIPOS', 'Equipos'), ('EPPS', 'EPPS'), ('MATERIALES', 'Materiales'), ('CONSUMIBLES', 'Consumibles'), ('HERRAMIENTAS', 'Herramientas')], max_length=100),
        ),
    ]
