# Generated by Django 5.1.1 on 2024-09-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0006_remove_product_type_remove_product_unit_measure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product_id',
            new_name='item_id',
        ),
    ]
