# Generated by Django 5.1.1 on 2024-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0007_rename_product_item_rename_product_id_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Equipo', 'Equipo'), ('EPPS', 'Epps'), ('Materiale', 'Material'), ('Consumible', 'Consumible'), ('Herramienta', 'Herramienta')], default='Equipo', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
