# Generated by Django 5.1.1 on 2024-09-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0008_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.CharField(choices=[('Equipo', 'Equipo'), ('EPPS', 'Epps'), ('Materiale', 'Material'), ('Consumible', 'Consumible'), ('Herramienta', 'Herramienta')], default='Equipo', max_length=100),
        ),
    ]
