# Generated by Django 5.1.1 on 2024-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0009_remove_item_category_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
