# Generated by Django 5.1.1 on 2024-09-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0011_alter_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='life_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
