# Generated by Django 5.1.1 on 2024-09-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0012_item_life_time_item_price_item_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.CharField(choices=[('Equipo', 'Equipo'), ('EPPS', 'Epps'), ('Material', 'Material'), ('Consumible', 'Consumible'), ('Herramienta', 'Herramienta')], default='Equipo', max_length=100),
        ),
    ]
