# Generated by Django 5.1.1 on 2024-09-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_inventory', '0015_alter_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic_inventory.subtype'),
        ),
    ]
