# Generated by Django 5.1.1 on 2024-09-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rank', models.CharField(max_length=50)),
                ('technician_class', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
            },
        ),
        migrations.CreateModel(
            name='TechnicianTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
                ('verb', models.CharField(max_length=50)),
                ('measurement', models.CharField(max_length=50)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Technician Task',
                'verbose_name_plural': 'Technician Tasks',
            },
        ),
        migrations.CreateModel(
            name='TechnicianCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(default='Taller AQP', max_length=50)),
                ('date', models.DateField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_control_technician.technician')),
            ],
            options={
                'verbose_name': 'Technician Card',
                'verbose_name_plural': 'Technician Cards',
                'unique_together': {('technician', 'station', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TechnicianCardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('technician_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='follow_control_technician.techniciancard')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_control_technician.techniciantask')),
            ],
            options={
                'verbose_name': 'Technician Card Task',
                'verbose_name_plural': 'Technician Card Tasks',
                'ordering': ['order'],
            },
        ),
    ]
