# Generated by Django 5.1.1 on 2024-09-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('follow_control_technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciancard',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.technician'),
        ),
        migrations.AlterModelOptions(
            name='techniciancard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='techniciancardtask',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='techniciantask',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='techniciancard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='techniciancardtask',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techniciancardtask',
            name='saler_order',
            field=models.CharField(default='cajahuanuco', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.RemoveField(
            model_name='techniciancard',
            name='station',
        ),
    ]
