# Generated by Django 5.1.1 on 2024-09-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_control_technician', '0005_alter_techniciancardtask_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciancardtask',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
