# Generated by Django 5.1.1 on 2024-09-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_requirements', '0001_initial'),
        ('logistic_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementorderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic_suppliers.suppliers'),
        ),
    ]
