# Generated by Django 5.1.1 on 2024-09-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
