# Generated by Django 5.1.1 on 2024-09-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_order_sales', '0006_purchaseorder_purchaseorderitem'),
        ('logistic_requirements', '0004_requirementorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementorder',
            name='total_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='requirementorderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requirementorderitem',
            name='sap_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementorder',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_orders', to='accounting_order_sales.salesorder'),
        ),
    ]
