# Generated by Django 5.1.1 on 2024-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_requirements', '0005_requirementorder_total_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementorder',
            name='purchase_order_created',
            field=models.BooleanField(default=False),
        ),
    ]
