# Generated by Django 5.1.1 on 2024-09-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_technical_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('medical_leave', 'Medical Leave'), ('retired', 'Retired')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='technical',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('medical_leave', 'Medical Leave'), ('retired', 'Retired')], default='active', max_length=50),
        ),
    ]
