# Generated by Django 5.1.1 on 2024-09-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_suppliers', '0002_alter_suppliers_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='interbank_currency',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cuenta Interbancaria'),
        ),
    ]
