# Generated by Django 5.1.1 on 2024-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_suppliers', '0003_alter_suppliers_interbank_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='currency',
            field=models.CharField(blank=True, choices=[('Soles', 'Soles'), ('Dólares', 'Dólares')], default='Soles', max_length=20, null=True, verbose_name='Moneda'),
        ),
    ]
