# Generated by Django 5.1.1 on 2024-09-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='legal_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
