# Generated by Django 5.1.1 on 2024-09-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_control_card', '0002_remove_task_client_remove_task_orden_venta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sale_order',
            new_name='saler_order',
        ),
    ]
