# Generated by Django 5.1.1 on 2024-09-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_control_card', '0003_rename_sale_order_task_saler_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='saler_order',
            new_name='sale_order',
        ),
    ]
